version: '3'

services:
  app:
    container_name: froide_app
    build: .
    volumes:
      - ./froide:/app/froide:rw
      - ./start.sh:/app/start.sh
      - ./local_settings.py:/app/froide/froide/local_settings.py:ro
    working_dir: /app/froide
    environment:
      DJANGO_SETTINGS_MODULE: froide.local_settings
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - default

  db:
    container_name: froide_db
    image: postgis/postgis:16-3.4
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: froide
      POSTGRES_DB: froide
      POSTGRES_PASSWORD: froide
    # ports:
    #   - "127.0.0.1:5432:5432"
    networks:
      - default

  elasticsearch:
    container_name: froide_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    volumes:
      - ./data/elasticsearch-data:/usr/share/elasticsearch/data
      - ./data/elasticsearch-log:/var/log
    environment:
      - "discovery.type=single-node"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "cluster.routing.allocation.disk.watermark.low=3gb"
      - "cluster.routing.allocation.disk.watermark.high=2gb"
      - "cluster.routing.allocation.disk.watermark.flood_stage=1gb"
      - "xpack.security.transport.ssl.enabled=false"
      - "xpack.security.http.ssl.enabled=false"
      - "xpack.security.enabled=false"
    # ports:
    #   - "127.0.0.1:9200:9200"
    networks:
      - default
